#!/usr/bin/env ruby
require 'rubygems'
require 'json'

if ARGV.size == 0
  puts "usage #{$0} input.wav"
  exit 1
end

input = ARGV[0]

system("./splitter -i #{input} -t 45 -d 0.3")
path = File.dirname(input)

results = []
confidence = 0
count = 0
root_name = File.basename(input).gsub(/\.wav$/,'')

# it's important that contiguous chunks stay connected otherwise partial words might be sent for transcribing
chunks = Dir["#{path}/#{root_name}*.wav.chunk*"].sort_by do|wave|
  wave.gsub(/.*\.chunk/,'').to_i
end

chunks.each do|wave|
  puts wave.inspect
  chunk_file = wave.gsub(/\.wav/,'') + ".wav"
  system("mv #{wave} #{chunk_file}")
  system("speech2text #{chunk_file}")
  wave_text = chunk_file.gsub(/\.wav$/,'.json')
  if File.exist?(wave_text)
    out = JSON.parse(File.read(wave_text))
    if out && out['captured_json'] && out['captured_json'].first
      results << out['captured_json'].first.first
      confidence += out['confidence']
      count += 1
    end
  end
end

if chunks.size == 0
  # send the original file
  system("speech2text #{input}")
  wave_text = input.gsub(/\.wav$/,'.json')
  if File.exist?(wave_text)
    out = JSON.parse(File.read(wave_text))
    if out && out['captured_json'] && out['captured_json'].first
      results << out['captured_json'].first.first
      confidence += out['confidence']
      count += 1
    end
  end
end

confidence /= count
puts results.join(" ")
puts confidence
